### ISSUE TITLE
Leverage prettier for documentation

### ISSUE THREAD

**Issue by gabegma** [ServiceNow/azimuth#123]

**Comment by gabegma** [comment]
Did you mention yesterday that you found a fix for that? Did you need to install something with yarn first?

**Comment by gabegma** [comment]
I tried with another hook and got relatively close to it working, but it doesn't handle complex admonitions with code/bullets/multiple tables in them.  I tabled this for now. 

```
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        exclude: docs/includes
        additional_dependencies:
          - mdformat-mkdocs
          - mdformat-admon
          - mdformat-beautysh
          - mdformat-footnote
          - mdformat-black
          - mdformat-simple-breaks
          - mdformat-tables

```
